feat: initial pass at object storage bucket resource
krystal/terraform-provider-katapult pull request #146
Opened 2024-10-23 14:05 UTC by ikadix

2026-05-04 20:27 UTC, ikadix commented on internal/v6provider/resource_object_storage_bucket.go
> +	}
in the api client we return an error that is checked before this point 

```
    if rsp.StatusCode < 200 || rsp.StatusCode >= 300 {
        return res, ErrRequestFailed
    }

```

2026-05-04 20:53 UTC, ikadix commented on mise.toml
> +lefthook = "latest"
lefthook still requires a manual install of hooks, pinning is not needed.

2026-05-08 13:48 UTC, ikadix commented
@coderabbitai review

2026-05-11 16:45 UTC, jimehk requested changes

2026-05-11 16:45 UTC, jimehk commented on internal/v6provider/testdata/ObjectStorageAccessKey_minimal.cassette.yaml
> +    body: '{"object_storage_access_key":{"id":"objkey_4q5ZuMlpwNsj0HnB","name":"tf-acc-test-minimal-y4bzbovptvdi","created_at":1777969109,"region":"uk-lon-1","state":"pending","all_buckets_read":fals
issue: The new object storage access key cassettes record live `s3_secret_access_key` values in response bodies. `AddSaveFilter` can mutate `cassette.Interaction.Response.Body` before the cassette is written, so we should redact these nested JSON values there rather than committing real generated credentials.

I’d suggest using a deterministic placeholder that incorporates the test rand ID, e.g. `redacted-${randID}`. That keeps replay stable and still lets us tell the fixture value is specific to this test run rather than an accidental provider hard-code. The runtime record path can still consume the real API response; only the saved cassette gets rewritten.

Suggested shape:

```go
r.AddSaveFilter(func(i *cassette.Interaction) error {
	delete(i.Request.Headers, "Authorization")

	var body map[string]any
	if err := json.Unmarshal([]byte(i.Response.Body), &body); err != nil {
		return nil
	}

	key, ok := body["object_storage_access_key"].(map[string]any)
	if !ok {
		return nil
	}

	if _, ok := key["s3_secret_access_key"]; ok {
		key["s3_secret_access_key"] = "redacted-" + randID
	}

	b, err := json.Marshal(body)
	if err != nil {
		return err
	}

	i.Response.Body = string(b)
	return nil
})
```

After adding that, the existing object storage access key cassettes should be rewritten so no real `s3_secret_access_key` values remain in git.

2026-05-11 16:45 UTC, jimehk commented on docs/resources/object_storage_bucket.md
> +  `public_list = false` to avoid exposing the object list).
issue: `public_list` must actually be set to true for serving static site,
without it the internal directory to index file translation will not work.

It does not however mean that directory listings become public, as internally
all requests which results in a directory get rewritten to the relevant index
filename instead.

2026-05-11 16:45 UTC, jimehk commented on lefthook.yml
> +
nitpick: The pre-commit lint checks this adds, actually fail on the extra
whitespace in this very file:

```
❯ git diff --check origin/main...HEAD
lefthook.yml:11: trailing whitespace.
+      
lefthook.yml:11: new blank line at EOF.
```

2026-05-13 09:28 UTC, ikadix commented
@coderabbitai resume

2026-08-11 16:24 UTC, jimehk commented
@coderabbitai review

2026-08-11 16:36 UTC, jimehk commented
@coderabbitai review

2026-08-12 13:31 UTC, jimehk approved these changes

2026-08-12 13:32 UTC, merged